#!/usr/bin/env zsh

# Globals

alias -g .....='cd ........'
alias -g ....='cd ......'
alias -g ...='cd....'
alias -g C='| tr "\n\r" "\0" | pbcopy'
alias -g G='| grep' # now you can do: ls foo G something
alias sudo='sudo ' # enable aliases to be sudo’ed

# File System

alias ......='cd ../../../../..'
alias .....='cd ../../../..'
alias ....='cd ../../..'
alias ...='cd ../..'
alias ..='cd ..'
alias cat='bat'
alias rmds='find . -type f -name "*.DS_Store" -ls -delete' # recursively delete `.DS_Store` files
alias cp='cp -i'
alias curdir='echo $(basename "$PWD" | tr -d "\n\r")'
alias diff='icdiff --highlight --line-numbers --show-all-spaces --whole-file'
alias du='du -h -d 2'
alias find='find -L'
alias gz='gzip -9n -v -S .gz'
alias la='EXA_COLORS="" | exa -l -a --git'
alias less='less -r'
alias ll='EXA_COLORS="" | exa -l --git'
alias ln='ln -v'
alias map='xargs -n1' # intuitive map function
alias mv='mv -i'
alias rm='rm -i' # nocorrect rm -i

# Network

alias localip='ipconfig getifaddr en0'
alias myip='echo $(wget http://ipinfo.io/ip -qO - | tr -d "\n\r")'
alias ports='sudo lsof -iTCP -sTCP:LISTEN -P'

# OS X

alias hide='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder' # hide hidden files in Finder
alias plistbuddy='/usr/libexec/PlistBuddy' # plistBuddy alias, because sometimes `defaults` just doesn’t cut it
alias show='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder' # show hidden files in Finder

# Shell

alias path='echo $PATH | tr -s ":" "\n\r"' # pretty print the path
