#!/usr/bin/env zsh

## Misc. Globals

alias -g .....='cd ........'
alias -g ....='cd ......'
alias -g ...='cd....'
alias -g C='| tr "\n" "\0" | pbcopy'
alias -g G='| grep' # now you can do: ls foo G something
# Enable aliases to be sudo’ed
alias sudo='sudo '

## File System

alias ......='cd ../../../../..'
alias .....='cd ../../../..'
alias ....='cd ../../..'
alias ...='cd ../..'
alias ..='cd ..'
alias cat='bat'
# Recursively delete `.DS_Store` files
alias cleands='find . -type f -name "*.DS_Store" -ls -delete'
alias cp='cp -i'
alias curdir='echo $(basename "$PWD" | tr -d "\n\r")'
alias diff='icdiff --highlight --line-numbers --show-all-spaces --whole-file'
alias du='du -h -d 2'
# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash='sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl'
alias find='find -L'
alias gz='gzip -9n -v -S .gz'
alias la='colourify ls -AFGhl'
alias less='less -r'
alias ll='colourify ls -FGhl'
alias ln='ln -v'
# Intuitive map function
alias map='xargs -n1'
alias mv='mv -i'
alias rm='rm -i' # nocorrect rm -i

## Network

alias localip='ipconfig getifaddr en0'
alias myip='echo $(wget http://ipinfo.io/ip -qO - | tr -d "\n")'
alias ports='sudo lsof -iTCP -sTCP:LISTEN -P'

## OS X

# Hide hidden files in Finder
alias hide='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'
# Clean up LaunchServices to remove duplicates in the “Open With” menu
alias lscleanup='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder'
# PlistBuddy alias, because sometimes `defaults` just doesn’t cut it
alias plistbuddy='/usr/libexec/PlistBuddy'
# Preview a file using QuickLook
alias ql='qlmanage -p 2>/dev/null' 
# Show hidden files in Finder
alias show='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'

## Security

# Pipe my public key to my clipboard.
alias pubkey='more ~/.ssh/id_rsa.pub | pbcopy'

## Shell

# Pretty print the path
alias path='echo $PATH | tr -s ":" "\n"'
