brew "bash"
brew "bat"
brew "brew-cask-completion"
brew "coreutils"
brew "curl", args: ["with-openssl"]
brew "diff-so-fancy"
brew "exa"
brew "findutils"
brew "git"
brew "gnu-sed", args: ["with-default-names"]
brew "gnu-tar"
brew "grc"
brew "grep", args: ["with-default-names"]
brew "icdiff"
brew "less"
brew "mas"
brew "moreutils"
brew "openssl@1.1"
brew "thefuck"
brew "tomanthony/brews/itermocil"
brew "vim", args: ["override-system-vi"]
brew "wget", args: ["with-iri"]
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
brew "zsh"
cask "alfred"
cask "appcleaner"
cask "bartender"
cask "brewservicesmenubar"
cask "caffeine"
cask "carbon-copy-cloner"
cask "crashplan"
cask "dropbox"
cask "flux"
cask "google-chrome"
cask "historyhound"
cask "iterm2"
cask "keka"
cask "macdown"
cask "popclip"
cask "private-internet-access"
cask "sizeup"
cask "visual-studio-code-insiders"
mas "Patterns", id: 429449079