#!/usr/bin/env zsh

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Link Homebrew casks in `/Applications` rather than `~/Applications`
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# PATH
export PATH="/usr/local/sbin:/usr/sbin:/sbin:$PATH"
export PATH="/usr/local/bin:/usr/bin:/bin:$PATH"
export PATH="$(brew --prefix)/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Eza
export EZA_COLORS="ur=37:uw=37:ux=37:ue=37:gr=37:gw=37:gx=37:tr=37:tw=37:tx=37:sn=38;5;240:sb=38;5;240:uu=1;38;5;10:un=38;5;10:da=38;5;25:di=38;5;75"

# Coreutils
if [ -n "$(brew --prefix coreutils)" ]; then
  export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
fi

# Curl
export PATH="$(brew --prefix curl)/bin:$PATH"

# Findutils
export PATH="$(brew --prefix findutils)/libexec/gnubin:$PATH"

# fzf
hash fzf &> /dev/null && source <(fzf --zsh)

# Grep
export PATH="$(brew --prefix grep)/libexec/gnubin:$PATH"

# OpenSSL
if [ -n "$(brew --prefix openssl@3)" ]; then
  export PATH="$(brew --prefix openssl@3)/bin:$PATH"
fi

# Sed
export PATH="$(brew --prefix gnu-sed)/libexec/gnubin:$PATH"

# Tar
export PATH="$(brew --prefix gnu-tar)/libexec/gnubin:$PATH"

# User (inc. bins supplied by this repo)
export PATH="$HOME/bin:$PATH"

# Exports PATH for in-project git repositories e.g. `./bin`
export PATH=".git/safe/../../bin:$PATH"
