#!/usr/bin/env zsh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='/usr/local/bin/code'
fi

# Link Homebrew casks in `/Applications` rather than `~/Applications`
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# System
export PATH="/usr/local/sbin:/usr/sbin:/sbin"
export PATH="/usr/local/bin:/usr/bin:/bin:$PATH"

# OpenSSL
export PATH="/usr/local/opt/openssl/bin:$PATH"

# fixes python build issue https://github.com/pyenv/pyenv/issues/993
export CFLAGS="-I$(brew --prefix openssl)/include $CFLAGS"
export LDFLAGS="-L$(brew --prefix openssl)/lib $LDFLAGS"

# GNU coreutils
# if [ -n "$(brew --prefix coreutils &> /dev/null)" ]; then
#   export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
# fi

# Node
export PATH="$HOME/.ndenv/shims:$PATH"
export PATH="$HOME/.ndenv/bin:$PATH"

# Python
export PATH="$HOME/Library/Python/2.7/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.pyenv/shims:$PATH"
export PATH="$(brew --prefix pyenv-virtualenv)/shims:$PATH"

# Ruby
export PATH="$HOME/.rbenv/shims:$PATH"

# PHP
export PATH="$(brew --prefix php)/bin:$PATH"
export PATH="$(brew --prefix php)/sbin:$PATH"
export PATH="$HOME/.composer/vendor/bin:$PATH"

# User
export PATH="$HOME/bin:$PATH"

# Project git repository
export PATH=".git/safe/../../bin:$PATH"
