#!/usr/bin/env zsh

# All the dig info
function digga() {
  dig +nocmd "$1" any +multiline +noall +answer
}

# `e` with no arguments opens the current directory in Sublime Text, otherwise
# opens the given location
function e() {
  if [ $# -eq 0 ]; then
    code .;
  else
    code "$@";
  fi;
}

# credit: http://nparikh.org/notes/zshrc.txt
# Usage: extract <file>
# Description: extracts archived files / mounts disk images
# Note: .dmg/hdiutil is Mac OS X-specific.
# function extract() {
#   if [ -f $1 ]; then
#     case $1 in
#       *.tar.bz2)  tar -jxvf $1                        ;;
#       *.tar.gz)   tar -zxvf $1                        ;;
#       *.bz2)      bunzip2 $1                          ;;
#       *.dmg)      hdiutil mount $1                    ;;
#       *.gz)       gunzip $1                           ;;
#       *.tar)      tar -xvf $1                         ;;
#       *.tbz2)     tar -jxvf $1                        ;;
#       *.tgz)      tar -zxvf $1                        ;;
#       *.zip)      unzip $1                            ;;
#       *.ZIP)      unzip $1                            ;;
#       *.pax)      cat $1 | pax -r                     ;;
#       *.pax.Z)    uncompress $1 --stdout | pax -r     ;;
#       *.Z)        uncompress $1                       ;;
#       *)          echo "'$1' cannot be extracted/mounted via extract()" ;;
#     esac
#   else
#     echo "'$1' is not a valid file"
#   fi
# }

# No arguments: `git status`
# With arguments: acts like `git`
unalias g
function g() {
  if [[ $# > 0 ]]; then
    git $@
  else
    if hash tig &> /dev/null; then
      tig status
    else
      git status
    fi
  fi
}

# Complete g like git
compdef g=git
compdef tig=git

# Create a new directory and enter it
function mkd() {
  mkdir -p "$@" && cd "$@"
}

# `o` with no arguments opens current directory, otherwise opens the given
# location
function o() {
  if [ $# -eq 0 ]; then
    open .
  else
    open "$@"
  fi
}

# Use percol to browser shell history
if which percol &> /dev/null; then
  function percol_select_history() {
    local tac
    exists gtac && tac="gtac" || { exists tac && tac="tac" || { tac="tail -r" } }
    BUFFER=$(fc -l -n 1 | eval $tac | percol --query "$LBUFFER" --match-method regex)
    CURSOR=$#BUFFER         # move cursor
    zle -R -c               # refresh
  }

  zle -N percol_select_history
  bindkey '^R' percol_select_history
fi

# Create a .tar.gz archive, using `zopfli`, `pigz` or `gzip` for compression
function targz() {
  local tmpFile="${@%/}.tar"
  tar -cvf "${tmpFile}" --exclude=".DS_Store" "${@}" || return 1

  size=$(
    stat -f"%z" "${tmpFile}" 2> /dev/null; # OS X `stat`
    stat -c"%s" "${tmpFile}" 2> /dev/null # GNU `stat`
  )

  local cmd=""
  if (( size < 52428800 )) && hash zopfli 2> /dev/null; then
    # the .tar file is smaller than 50 MB and Zopfli is available; use it
    cmd="zopfli"
  else
    if hash pigz 2> /dev/null; then
      cmd="pigz"
    else
      cmd="gzip"
    fi
  fi

  echo "Compressing .tar using \`${cmd}\`…"
  "${cmd}" -v "${tmpFile}" || return 1
  [ -f "${tmpFile}" ] && rm "${tmpFile}"
  echo "${tmpFile}.gz created successfully."
}

# `v` with no arguments opens the current directory in Vim, otherwise opens the
# given location
function v() {
  if [ $# -eq 0 ]; then
    vim .
  else
    vim "$@"
  fi
}
