#!/usr/bin/env zsh

#   alt + left   : move to next word (below)
#   alt + right  : move to previous word (below)

#   ctrl + w     : delete word backward
#   ctrl + r     : reverse search with fzf
#   ctrl + t     : search current directory with fzf and use path on the command line
#   ctrl + y     : insert last deleted word
#   ctrl + u     : clear line
#   ctrl + i     : insert TAB
#   ctrl + a     : move to beginning of line
#   ctrl + h     : reverse search with percol
#   ctrl + k     : delete from character to end of line
#   ctrl + x     : insert last command result (below)
#   ctrl + z     : browse z history with fzf
#   ctrl + c     : cancel
#   ctrl + n     : clear line
#   ctrl + space : git status (below)

#   fn + left    : move to beginning of line
#   fn + right   : move to end of line

bindkey -e

# alt + left/right : back/forward one word
bindkey '^[^[[D' backward-word
bindkey '^[^[[C' forward-word

# Use percol to browser shell history
if which percol &> /dev/null; then
  function percol_select_history() {
    BUFFER=$(fc -l -n 1 | gtac | percol --query "$LBUFFER" --match-method regex)
    CURSOR=$#BUFFER         # move cursor
    zle -R -c               # refresh
  }

  zle -N percol_select_history
  bindkey '^H' percol_select_history
fi

# ctrl + x : insert last command result
zmodload -i zsh/parameter
insert-last-command-output() {
  LBUFFER+="$(eval $history[$((HISTCMD-1))])"
}
zle -N insert-last-command-output
bindkey '^X' insert-last-command-output

# ctrl + space : tig status
bindkey -s '^ ' 'tig status^M'
