#!/usr/bin/env zsh

#   alt + left   : move to previous word (below)
#   alt + right  : move to next word (below)

#   ctrl + w     : delete word backward
#   ctrl + r     : reverse search with fzf
#   ctrl + t     : search current directory with fzf and use path on the command line
#   ctrl + y     : insert last deleted word
#   ctrl + u     : clear line
#   ctrl + i     : insert TAB
#   ctrl + a     : move to beginning of line
#   ctrl + g     : abort / send-break
#   ctrl + k     : delete from character to end of line
#   ctrl + l     : clear screen
#   ctrl + x     : insert last command result (below)
#   ctrl + z     : browse zoxide history with fzf
#   ctrl + c     : cancel
#   ctrl + b     : go back to previous directory
#   ctrl + space : tig status (below)

#   fn + left    : move to beginning of line
#   fn + right   : move to end of line

bindkey -e

# alt + left/right : back/forward one word
bindkey '^[^[[D' backward-word
bindkey '^[^[[C' forward-word

# ctrl + x : insert last command result
zmodload -i zsh/parameter
insert-last-command-output() {
  LBUFFER+=$(eval "${history[$[HISTCMD-1]]}")
}
zle -N insert-last-command-output
bindkey '^X' insert-last-command-output

# ctrl + b : go back to previous directory
bindkey -s '^B' 'cd -^M'

# ctrl + space : tig status
bindkey -s '^ ' 'tig status^M'
