cask "appcleaner"
cask "apptrap"
cask "blockblock"
cask "caffeine"
cask "do-not-disturb"
cask "keka"
cask "knockknock"
cask "linearmouse"
cask "lulu"
cask "mullvadvpn"
cask "netiquette"
cask "oversight"
cask "reikey"
cask "taskexplorer"
mas "PopClip", id: 445189367
