brew "ffmpeg"
brew "rigellute/tap/spotify-tui"
brew "spotifyd"
brew "yt-dlp/taps/yt-dlp"
cask "beamer"
cask "handbrake"
cask "iina"
cask "losslesscut"
cask "soundcast"
cask "soundflower"
cask "soundflowerbed"
cask "spotify-notifications"
cask "spotify-now-playing"
mas "Helium", id: 1054607607
